### ISSUE TITLE
Eclipse到进入编译不过啊

### ISSUE THREAD

**Issue by lis2013** [AppCanOpenSource/appcan-android#1]
1. 是不是一些依赖库没有上传？ 2. AppCanBaseProject 是干嘛用的了？

**Comment by letheliu** [comment]
AppCanBaseProject为什么不能直接运行，提示：“程序无法加载必须的资源文件或缺少必须的组件，请检查是否误删，程序将退出”

**Comment by AppCanOpenSource** [comment]
你用的哪个工程？

**Comment by letheliu** [comment]
en_baseEngineProject

**Comment by AppCanOpenSource** [comment]
应该是用Engine目录下面的工程。

**Comment by letheliu** [comment]
ok, 可以了，谢谢！！！

**Comment by letheliu** [comment]
ok, 可以了，谢谢！！！

**Comment by letheliu** [comment]
ok, 可以了，谢谢！！！
