### ISSUE TITLE
            appPath += appPath + "/" or             appPath = appPath + "/";

### ISSUE THREAD

**Issue by lotosbin** [AppCanOpenSource/appcan-android#143]
https://github.com/AppCanOpenSource/appcan-android/blob/a39441052391adfc677a6e1f117678e21e657641/Engine/src/main/java/org/zywx/wbpalmstar/widgetone/dataservice/WDataManager.java#L569

**Comment by sandy1108** [comment]
谢谢反馈。你说的这个地方看起来好像确实有点问题，应该就是为了补充一个斜杠而已。不过由于这个方法的调用者uexWidget.startWidgetWithPath接口已经基本弃用，所以这个bug一直也没有暴露出来。
