### ISSUE TITLE
拷贝到新工程按照步骤出现以下build错误

### ISSUE THREAD

**Issue by Lyang166** [AppCanOpenSource/appcan-android#153]
* What went wrong:
Task 'buildEngine' not found in root project 'Engine_AppCan'.

**Comment by aixiaozi** [comment]
也遇到这个问题了，@sandy1108  能帮忙看下吗？

**Comment by sandy1108** [comment]
用AS打开工程的时候，要选择Engine那个文件夹，那个才是主工程。外面的git仓库不是工程。没有配置gradle。

**Comment by sandy1108** [comment]
用AS打开工程的时候，要选择Engine那个文件夹，那个才是主工程。外面的git仓库不是工程。没有配置gradle。

**Comment by aixiaozi** [comment]
@sandy1108 , 我就是在 `Engine` 目录下运行的 `gradle buildEngine` 命令：
```
C:\Users\username\AndroidStudioProjects\Engine_AppCan\appcan-android\Engine>gradle buildEngine
```

Error:

```
> Configure project :appcan-android:Engine
AppCanEngine version is 4.3.21
AppCanEngine current buildVersion is 01
apply appcan error???
?????Run?????????????????????????Gradle?????Android?????Instant Run???buildEngine Task???????????????????Instant Run?????????

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildEngine' not found in project ':appcan-android:Engine'.
```

**Comment by aixiaozi** [comment]
@sandy1108 , 搜索到 @yltwust 16年的代码提交记录： [更改buildEngine task名称](https://github.com/AppCanOpenSource/appcan-android/commit/8ca49b61eb0e9eb483498fead64a02d0083656fe#diff-1a2acb60e38bfdb002f5f0090ee8dbcc)，是修改了 task 名称？

**Comment by sandy1108** [comment]
> @sandy1108 , 我就是在 `Engine` 目录下运行的 `gradle buildEngine` 命令：
> 
> ```
> C:\Users\username\AndroidStudioProjects\Engine_AppCan\appcan-android\Engine>gradle buildEngine
> ```
> 
> Error:
> 
> ```
> > Configure project :appcan-android:Engine
> AppCanEngine version is 4.3.21
> AppCanEngine current buildVersion is 01
> apply appcan error???
> ?????Run?????????????????????????Gradle?????Android?????Instant Run???buildEngine Task???????????????????Instant Run?????????
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'buildEngine' not found in project ':appcan-android:Engine'.
> ```

你这个错误不一样。你的终端最好设置成UTF-8的，要不然问号你看不出来是啥。实际上我代码里写的是提示你把InstantRun关掉试试。

**Comment by aixiaozi** [comment]
@sandy1108 , 关掉 InstantRun 了还是报一样的错，编码的问题试了许多方案还是乱码。我把项目 share 到[这](https://github.com/aixiaozi/Engine_AppCan)了，能帮忙看一下吗？

**Comment by aixiaozi** [comment]
@sandy1108 , 我在 `Engine` 目录下也没有发现  `buildEngine` task 啊。。。

**Comment by aixiaozi** [comment]
@sandy1108 可以帮忙看下这个问题吗？可以有偿。。。

**Comment by sandy1108** [comment]
这个问题没这么复杂吧？全新clone一个引擎仓库下来，然后打开AS的时候，不要选择之前已经打开的工程，直接File，Open，选择Engine文件夹，只有Engine这个文件夹才是真工程。然后gradle同步完成后就ok了啊。

**Comment by aixiaozi** [comment]
@sandy1108 , 谢谢，这个问题解决了。另外一个屏幕适配的问题想问一下，需要新开一个 issue 吗？

问题是这样的，我们的项目要适配三个屏幕，在 800*1080 和 720*1280 的机器上都显示的很好，但是在另一个 1280*1920 的机器上显示的效果很差，所以我们需要做屏幕适配。我想用 [像素密度](https://mp.weixin.qq.com/s/d9QCoBP6kV9VSWvVldVVwA) 适配的方式来适配我们的 AppCan 项目，但是没有任何效果，想请问一下这个方案对于 AppCan 项目来说是否可行，如果不行的话那通常 AppCan 项目的屏幕适配都是如何来做的呢？能加个好友吗？万分感激

**Comment by aixiaozi** [comment]
@sandy1108 , 能帮忙看一下吗？真的很需要你的帮助
